version: '3'
services:
  e-commerce-laravel:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: darmshot/e-commerce-laravel
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
    volumes:
      - './storage:/var/www/html/storage'
    environment:
      WWWUSER: '${WWWUSER}'
    networks:
      - e-commerce-laravel-network
    depends_on:
      - mysql
      - redis
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'e-commerce-laravel-mysql:/var/lib/mysql'
      - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
    networks:
      - e-commerce-laravel-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s
  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'e-commerce-laravel-redis:/data'
    networks:
      - e-commerce-laravel-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s
networks:
  e-commerce-laravel-network:
    driver: bridge
volumes:
  e-commerce-laravel-mysql:
    driver: local
  e-commerce-laravel-redis:
    driver: local
